/**
 * Tests for MCP Sprint tools - Sprint validations (PMC-TSK-0062)
 *
 * AC1: Creating a task with sprint assigned → error (sprint assigned on In Progress)
 * AC2: Only first sprint can have startDate/endDate
 * AC3: Moving task to In Progress with date outside sprint range → error
 * AC4: Sprint with In Progress/To Validate tasks → dates immutable
 * AC5: Sprint with In Progress tasks → locked=true
 * Plus: AI duration warning for sprint creation
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';

// Mock firebase-adapter
const mockOnce = vi.fn();
const mockSet = vi.fn().mockResolvedValue();
const mockUpdate = vi.fn().mockResolvedValue();
const mockPush = vi.fn();
const mockRef = vi.fn();
const mockTransaction = vi.fn();

vi.mock('../../mcp/firebase-adapter.js', () => ({
  getDatabase: () => ({
    ref: mockRef
  }),
  getFirestore: () => ({
    collection: () => ({
      doc: () => ({})
    }),
    runTransaction: mockTransaction
  })
}));

// Default: AI user (geniova-mcp)
let mockUserId = 'geniova-mcp';
vi.mock('../../mcp/user.js', () => ({
  getMcpUserId: () => mockUserId,
  getMcpUser: () => ({ email: 'test@example.com', developerId: 'dev_001' }),
  isMcpUserConfigured: () => true
}));

// Mock list-service to avoid Firebase RTDB calls for resolveValue
vi.mock('../../mcp/services/list-service.js', () => ({
  getListTexts: vi.fn().mockResolvedValue([]),
  getListPairs: vi.fn().mockResolvedValue([]),
  resolveValue: vi.fn().mockImplementation((listType, value) => Promise.resolve(value))
}));

const { createSprint, updateSprint } = await import('../../mcp/tools/sprints.js');
const { createCard, updateCard } = await import('../../mcp/tools/cards.js');

function setupMockRef(abbreviation = 'TST', extraHandlers = {}) {
  const pushKey = '-newSprintKey';
  mockPush.mockReturnValue({
    key: pushKey,
    set: mockSet
  });

  mockRef.mockImplementation((path) => {
    if (path.includes('/abbreviation')) {
      return {
        once: vi.fn().mockResolvedValue({ val: () => abbreviation })
      };
    }
    // Allow custom handlers by path pattern (check longest patterns first)
    const sortedPatterns = Object.keys(extraHandlers).sort((a, b) => b.length - a.length);
    for (const pattern of sortedPatterns) {
      if (path.includes(pattern)) {
        return extraHandlers[pattern](path);
      }
    }
    return {
      once: mockOnce,
      set: mockSet,
      update: mockUpdate,
      push: () => mockPush()
    };
  });

  // Mock Firestore transaction for counter
  mockTransaction.mockImplementation(async (fn) => {
    const mockDocSnap = { exists: true, data: () => ({ lastId: 5 }) };
    const mockTransactionObj = {
      get: vi.fn().mockResolvedValue(mockDocSnap),
      set: vi.fn()
    };
    return fn(mockTransactionObj);
  });
}

// ──────────────────────────────────────────────
// Sprint = 1 day strict policy (PMC-TSK-0072)
// ──────────────────────────────────────────────
describe('MCP Sprint tools - Sprint = 1 day strict policy', () => {
  const NOW = new Date('2026-06-07T15:30:00.000Z');
  const BOUNDS = {
    startDate: '2026-06-07T00:00:00.000Z',
    endDate: '2026-06-07T23:59:59.999Z'
  };

  beforeEach(() => {
    vi.clearAllMocks();
    mockUserId = 'geniova-mcp';
  });

  it('auto-generates the title as "Sprint N - YYYYMMDD" when none is provided', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({ val: () => null }); // no existing sprints

    const result = await createSprint(
      { projectId: 'TestProject' },
      { now: NOW }
    );

    const data = JSON.parse(result.content[0].text);
    expect(data.message).toBe('Sprint created successfully');
    expect(data.title).toBe('Sprint 1 - 20260607');
    expect(data.startDate).toBe(BOUNDS.startDate);
    expect(data.endDate).toBe(BOUNDS.endDate);
    expect(data.durationDays).toBe(1);
    expect(data.autoGenerated).toBe(true);
  });

  it('uses next-of-year correlative based on existing sprints', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({
      val: () => ({
        '-a': { startDate: '2026-01-02T00:00:00.000Z', title: 'Sprint 1 - 20260102' },
        '-b': { startDate: '2026-03-15T00:00:00.000Z', title: 'Sprint 17 - 20260315' },
        '-legacy': { startDate: '2026-02-01', title: 'Sprint Global 2026' } // unparseable
      })
    });

    const result = await createSprint(
      { projectId: 'TestProject' },
      { now: NOW }
    );

    const data = JSON.parse(result.content[0].text);
    expect(data.title).toBe('Sprint 18 - 20260607');
  });

  it('appends optional suffix when auto-generating', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({ val: () => null });

    const result = await createSprint(
      { projectId: 'TestProject', suffix: 'Foundations' },
      { now: NOW }
    );

    const data = JSON.parse(result.content[0].text);
    expect(data.title).toBe('Sprint 1 - 20260607 - Foundations');
  });

  it('accepts an explicit title that conforms to the format', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({ val: () => null });

    const result = await createSprint(
      { projectId: 'TestProject', title: 'Sprint 42 - 20260607 - Hotfix' },
      { now: NOW }
    );

    const data = JSON.parse(result.content[0].text);
    expect(data.title).toBe('Sprint 42 - 20260607 - Hotfix');
    expect(data.autoGenerated).toBe(false);
  });

  it('rejects an explicit title that does not conform', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({ val: () => null });

    await expect(createSprint(
      { projectId: 'TestProject', title: 'Sprint 1 - June 2026' },
      { now: NOW }
    )).rejects.toThrow(/invalid sprint title/i);
  });

  it('respects explicit startDate and endDate when both are provided', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({ val: () => null });

    const result = await createSprint(
      {
        projectId: 'TestProject',
        startDate: '2026-07-10',
        endDate: '2026-07-14'
      },
      { now: NOW }
    );

    const data = JSON.parse(result.content[0].text);
    expect(data.startDate).toBe('2026-07-10T00:00:00.000Z');
    expect(data.endDate).toBe('2026-07-14T23:59:59.999Z');
    expect(data.durationDays).toBe(5);
    expect(data.title).toBe('Sprint 1 - 20260710');
    expect(data.autoGenerated).toBe(true);
    expect(data.warnings).toBeUndefined();
  });

  it('treats a single startDate without endDate as a 1-day sprint on that day', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({ val: () => null });

    const result = await createSprint(
      { projectId: 'TestProject', startDate: '2026-07-10' },
      { now: NOW }
    );

    const data = JSON.parse(result.content[0].text);
    expect(data.startDate).toBe('2026-07-10T00:00:00.000Z');
    expect(data.endDate).toBe('2026-07-10T23:59:59.999Z');
    expect(data.durationDays).toBe(1);
    expect(data.title).toBe('Sprint 1 - 20260710');
  });

  it('uses today as start when only endDate is provided', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({ val: () => null });

    const result = await createSprint(
      { projectId: 'TestProject', endDate: '2026-06-09' },
      { now: NOW }
    );

    const data = JSON.parse(result.content[0].text);
    expect(data.startDate).toBe(BOUNDS.startDate);
    expect(data.endDate).toBe('2026-06-09T23:59:59.999Z');
    expect(data.durationDays).toBe(3);
  });

  it('rejects endDate before startDate', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({ val: () => null });

    await expect(createSprint(
      {
        projectId: 'TestProject',
        startDate: '2026-07-10',
        endDate: '2026-07-05'
      },
      { now: NOW }
    )).rejects.toThrow(/endDate.*on or after.*startDate/i);
  });

  it('rejects unparseable startDate', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({ val: () => null });

    await expect(createSprint(
      { projectId: 'TestProject', startDate: 'not-a-date' },
      { now: NOW }
    )).rejects.toThrow(/Invalid startDate/i);
  });

  it('includes the sprint policy note in the response', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({ val: () => null });

    const result = await createSprint(
      { projectId: 'TestProject' },
      { now: NOW }
    );

    const data = JSON.parse(result.content[0].text);
    expect(data.policy).toMatch(/Sprint = 1 day of work by default/i);
    expect(data.policy).toMatch(/not Scrum/i);
  });

  it('is idempotent: returns the existing sprint of today instead of creating a duplicate', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({
      val: () => ({
        '-todays': {
          cardId: 'TST-SPR-0099',
          title: 'Sprint 7 - 20260607',
          startDate: BOUNDS.startDate,
          endDate: BOUNDS.endDate
        }
      })
    });

    const result = await createSprint(
      { projectId: 'TestProject' },
      { now: NOW }
    );

    const data = JSON.parse(result.content[0].text);
    expect(data.idempotent).toBe(true);
    expect(data.cardId).toBe('TST-SPR-0099');
    expect(data.title).toBe('Sprint 7 - 20260607');
    expect(mockSet).not.toHaveBeenCalled(); // no new sprint persisted
  });

  it('warns when suffix is passed together with an explicit title', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({ val: () => null });

    const result = await createSprint(
      { projectId: 'TestProject', title: 'Sprint 1 - 20260607', suffix: 'Ignored' },
      { now: NOW }
    );

    const data = JSON.parse(result.content[0].text);
    expect(data.title).toBe('Sprint 1 - 20260607');
    expect(data.warnings).toEqual(expect.arrayContaining([
      expect.stringMatching(/Ignored "suffix"/i)
    ]));
  });
});

// ──────────────────────────────────────────────
// AC4: Sprint dates immutable when tasks active
// ──────────────────────────────────────────────
describe('MCP Sprint tools - AC4: Immutable dates with active tasks', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockUserId = 'geniova-mcp';
  });

  it('should reject date change when sprint has In Progress tasks', async () => {
    const sprintCardId = 'TST-SPR-0001';
    const sprintFirebaseId = '-sprint1';

    const sprintOnce = vi.fn().mockResolvedValue({
      exists: () => true,
      val: () => ({
        cardId: sprintCardId,
        title: 'Sprint 1',
        startDate: '2026-03-01',
        endDate: '2026-03-15'
      })
    });
    const taskOnce = vi.fn().mockResolvedValue({
      val: () => ({
        '-task1': {
          cardId: 'TST-TSK-0001',
          status: 'In Progress',
          sprint: sprintCardId
        }
      })
    });

    setupMockRef('TST', {
      [`SPRINTS_TestProject/${sprintFirebaseId}`]: () => ({
        once: sprintOnce,
        update: mockUpdate
      }),
      ['TASKS_TestProject']: () => ({
        once: taskOnce
      })
    });

    await expect(updateSprint({
      projectId: 'TestProject',
      firebaseId: sprintFirebaseId,
      updates: { startDate: '2026-03-05' }
    })).rejects.toThrow(/immutable|cannot.*change.*date/i);
  });

  it('should reject date change when sprint has To Validate tasks', async () => {
    const sprintCardId = 'TST-SPR-0001';
    const sprintFirebaseId = '-sprint1';

    const sprintOnce = vi.fn().mockResolvedValue({
      exists: () => true,
      val: () => ({
        cardId: sprintCardId,
        title: 'Sprint 1',
        startDate: '2026-03-01',
        endDate: '2026-03-15'
      })
    });
    const taskOnce = vi.fn().mockResolvedValue({
      val: () => ({
        '-task1': {
          cardId: 'TST-TSK-0001',
          status: 'To Validate',
          sprint: sprintCardId
        }
      })
    });

    setupMockRef('TST', {
      [`SPRINTS_TestProject/${sprintFirebaseId}`]: () => ({
        once: sprintOnce,
        update: mockUpdate
      }),
      ['TASKS_TestProject']: () => ({
        once: taskOnce
      })
    });

    await expect(updateSprint({
      projectId: 'TestProject',
      firebaseId: sprintFirebaseId,
      updates: { endDate: '2026-03-20' }
    })).rejects.toThrow(/immutable|cannot.*change.*date/i);
  });

  it('should allow date change when sprint has no active tasks', async () => {
    const sprintCardId = 'TST-SPR-0001';
    const sprintFirebaseId = '-sprint1';

    const sprintData = {
      cardId: sprintCardId,
      title: 'Sprint 1',
      startDate: '2026-03-01',
      endDate: '2026-03-15'
    };

    const sprintOnce = vi.fn()
      .mockResolvedValueOnce({
        exists: () => true,
        val: () => ({ ...sprintData })
      })
      .mockResolvedValueOnce({
        val: () => ({ ...sprintData, startDate: '2026-03-05' })
      });
    const taskOnce = vi.fn().mockResolvedValue({
      val: () => ({
        '-task1': {
          cardId: 'TST-TSK-0001',
          status: 'Done',
          sprint: sprintCardId
        }
      })
    });

    setupMockRef('TST', {
      [`SPRINTS_TestProject/${sprintFirebaseId}`]: () => ({
        once: sprintOnce,
        update: mockUpdate
      }),
      ['TASKS_TestProject']: () => ({
        once: taskOnce
      })
    });

    const result = await updateSprint({
      projectId: 'TestProject',
      firebaseId: sprintFirebaseId,
      updates: { startDate: '2026-03-05' }
    });

    const data = JSON.parse(result.content[0].text);
    expect(data.message).toBe('Sprint updated successfully');
  });
});

// ──────────────────────────────────────────────
// AC1: Reject sprint in createCard for tasks
// ──────────────────────────────────────────────
describe('MCP Sprint tools - AC1: Reject sprint on task creation', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockUserId = 'geniova-mcp';
  });

  it('should reject creating a task with sprint assigned', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({
      val: () => ({
        '-epic1': {
          cardId: 'TST-EPC-0001',
          title: 'Epic 1',
          status: 'Open'
        }
      })
    });

    await expect(createCard({
      projectId: 'TestProject',
      type: 'task',
      title: 'Test task',
      descriptionStructured: [{ role: 'developer', goal: 'test', benefit: 'testing' }],
      acceptanceCriteriaStructured: [{ given: 'ctx', when: 'act', then: 'res' }],
      epic: 'TST-EPC-0001',
      sprint: 'TST-SPR-0001'
    })).rejects.toThrow(/sprint.*In Progress|sprint.*assigned.*In Progress/i);
  });

  it('should allow creating a task without sprint', async () => {
    setupMockRef();
    mockOnce.mockResolvedValue({
      val: () => ({
        '-epic1': {
          cardId: 'TST-EPC-0001',
          title: 'Epic 1',
          status: 'Open'
        }
      })
    });

    const result = await createCard({
      projectId: 'TestProject',
      type: 'task',
      title: 'Test task',
      descriptionStructured: [{ role: 'developer', goal: 'test', benefit: 'testing' }],
      acceptanceCriteriaStructured: [{ given: 'ctx', when: 'act', then: 'res' }],
      epic: 'TST-EPC-0001',
      validator: 'stk_001'
    });

    const data = JSON.parse(result.content[0].text);
    expect(data.message).toBe('Card created successfully');
  });

  it('should allow creating a bug with sprint (no restriction for bugs)', async () => {
    setupMockRef();
    // Mock sprint exists
    mockOnce.mockResolvedValue({
      val: () => ({
        '-sprint1': {
          cardId: 'TST-SPR-0001',
          title: 'Sprint 1'
        }
      })
    });

    const result = await createCard({
      projectId: 'TestProject',
      type: 'bug',
      title: 'Test bug',
      description: 'A bug description',
      sprint: 'TST-SPR-0001'
    });

    const data = JSON.parse(result.content[0].text);
    expect(data.message).toBe('Card created successfully');
  });
});

// ──────────────────────────────────────────────
// AC3: Validate sprint date range on In Progress
// ──────────────────────────────────────────────
describe('MCP Sprint tools - AC3: Sprint date range on In Progress', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockUserId = 'geniova-mcp';
  });

  it('should reject moving task to In Progress when today is outside sprint date range', async () => {
    const taskFirebaseId = '-task1';
    const sprintCardId = 'TST-SPR-0001';

    const taskOnce = vi.fn().mockResolvedValue({
      exists: () => true,
      val: () => ({
        cardId: 'TST-TSK-0001',
        title: 'Test task',
        status: 'To Do',
        sprint: sprintCardId,
        developer: 'dev_001',
        validator: 'stk_001',
        devPoints: 2,
        businessPoints: 3,
        acceptanceCriteria: 'Some criteria',
        epic: 'TST-EPC-0001'
      })
    });
    const sprintOnce = vi.fn().mockResolvedValue({
      val: () => ({
        '-sprint1': {
          cardId: sprintCardId,
          title: 'Sprint 1',
          startDate: '2025-01-01',
          endDate: '2025-01-15'
        }
      })
    });

    setupMockRef('TST', {
      [`TASKS_TestProject/${taskFirebaseId}`]: () => ({
        once: taskOnce,
        update: mockUpdate
      }),
      ['SPRINTS_TestProject']: () => ({
        once: sprintOnce
      }),
      ['/scoringSystem']: () => ({
        once: vi.fn().mockResolvedValue({ val: () => '1-5' })
      })
    });

    await expect(updateCard({
      projectId: 'TestProject',
      type: 'task',
      firebaseId: taskFirebaseId,
      updates: {
        status: 'In Progress',
        developer: 'dev_001',
        validator: 'stk_001',
        sprint: sprintCardId,
        devPoints: 2,
        businessPoints: 3,
        acceptanceCriteria: 'Some criteria',
        epic: 'TST-EPC-0001'
      }
    })).rejects.toThrow(/sprint.*date|date.*sprint/i);
  });

  it('should allow moving task to In Progress when sprint has no dates (skip validation)', async () => {
    const taskFirebaseId = '-task1';
    const sprintCardId = 'TST-SPR-0001';
    const sprintFirebaseId = '-sprint1';

    const taskData = {
      cardId: 'TST-TSK-0001',
      title: 'Test task',
      status: 'To Do',
      sprint: sprintCardId,
      developer: 'dev_001',
      validator: 'stk_001',
      devPoints: 2,
      businessPoints: 3,
      acceptanceCriteria: 'Some criteria',
      epic: 'TST-EPC-0001'
    };

    const taskOnce = vi.fn()
      .mockResolvedValueOnce({
        exists: () => true,
        val: () => ({ ...taskData })
      })
      .mockResolvedValueOnce({
        val: () => ({ ...taskData, status: 'In Progress' })
      });
    const sprintOnce = vi.fn().mockResolvedValue({
      val: () => ({
        [sprintFirebaseId]: {
          cardId: sprintCardId,
          title: 'Sprint 1'
          // No startDate/endDate
        }
      })
    });
    const sprintItemUpdate = vi.fn().mockResolvedValue();

    setupMockRef('TST', {
      [`TASKS_TestProject/${taskFirebaseId}`]: () => ({
        once: taskOnce,
        update: mockUpdate
      }),
      ['SPRINTS_TestProject']: (path) => {
        if (path.includes(sprintFirebaseId)) {
          return { update: sprintItemUpdate };
        }
        return { once: sprintOnce, update: sprintItemUpdate };
      },
      ['/scoringSystem']: () => ({
        once: vi.fn().mockResolvedValue({ val: () => '1-5' })
      })
    });

    const result = await updateCard({
      projectId: 'TestProject',
      type: 'task',
      firebaseId: taskFirebaseId,
      updates: {
        status: 'In Progress',
        developer: 'dev_001',
        validator: 'stk_001',
        sprint: sprintCardId,
        devPoints: 2,
        businessPoints: 3,
        acceptanceCriteria: 'Some criteria',
        epic: 'TST-EPC-0001'
      }
    });

    const data = JSON.parse(result.content[0].text);
    expect(data.message).toBe('Card updated successfully');
  });
});

// ──────────────────────────────────────────────
// AC5: Auto-lock sprint on In Progress
// ──────────────────────────────────────────────
describe('MCP Sprint tools - AC5: Auto-lock sprint on In Progress', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockUserId = 'geniova-mcp';
  });

  it('should set locked=true on sprint when task moves to In Progress', async () => {
    const taskFirebaseId = '-task1';
    const sprintCardId = 'TST-SPR-0001';
    const sprintFirebaseId = '-sprint1';
    const today = new Date().toISOString().split('T')[0];

    const sprintUpdateMock = vi.fn().mockResolvedValue();
    const taskData = {
      cardId: 'TST-TSK-0001',
      title: 'Test task',
      status: 'To Do',
      sprint: sprintCardId,
      developer: 'dev_001',
      validator: 'stk_001',
      devPoints: 2,
      businessPoints: 3,
      acceptanceCriteria: 'Some criteria',
      epic: 'TST-EPC-0001'
    };

    const taskOnce = vi.fn()
      .mockResolvedValueOnce({
        exists: () => true,
        val: () => ({ ...taskData })
      })
      .mockResolvedValueOnce({
        val: () => ({ ...taskData, status: 'In Progress' })
      });
    const sprintOnce = vi.fn().mockResolvedValue({
      val: () => ({
        [sprintFirebaseId]: {
          cardId: sprintCardId,
          title: 'Sprint 1',
          startDate: today,
          endDate: '2099-12-31'
        }
      })
    });

    setupMockRef('TST', {
      [`TASKS_TestProject/${taskFirebaseId}`]: () => ({
        once: taskOnce,
        update: mockUpdate
      }),
      ['SPRINTS_TestProject']: (path) => {
        if (path.includes(sprintFirebaseId)) {
          return { update: sprintUpdateMock };
        }
        return { once: sprintOnce, update: sprintUpdateMock };
      },
      ['/scoringSystem']: () => ({
        once: vi.fn().mockResolvedValue({ val: () => '1-5' })
      })
    });

    await updateCard({
      projectId: 'TestProject',
      type: 'task',
      firebaseId: taskFirebaseId,
      updates: {
        status: 'In Progress',
        developer: 'dev_001',
        validator: 'stk_001',
        sprint: sprintCardId,
        devPoints: 2,
        businessPoints: 3,
        acceptanceCriteria: 'Some criteria',
        epic: 'TST-EPC-0001'
      }
    });

    // Verify sprint was updated with locked=true
    expect(sprintUpdateMock).toHaveBeenCalledWith(
      expect.objectContaining({ locked: true })
    );
  });
});
